export default [
    {
        team: "liverpool",
        points: 6,
        matches_played: 2,
        wins: 2,
        draws: 0,
        losses: 0,
        goals_for: 5,
        goals_against: 0,
        goal_difference: 5
    },
    {
        team: "manchester united",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 5,
        goals_against: 1,
        goal_difference: 4
    },
    {
        team: "chelsea",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 3,
        goals_against: 0,
        goal_difference: 3
    },
    {
        team: "west ham",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 4,
        goals_against: 2,
        goal_difference: 2
    },
    {
        team: "everton",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 3,
        goals_against: 1,
        goal_difference: 2
    },
    {
        team: "brentford",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 2,
        goals_against: 0,
        goal_difference: 2
    },
    {
        team: "watford",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 3,
        goals_against: 2,
        goal_difference: 1
    },
    {
        team: "brighton",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 2,
        goals_against: 1,
        goal_difference: 1
    },
    {
        team: "leicester city",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 1,
        goals_against: 0,
        goal_difference: 1
    },
    {
        team: "tottenham",
        points: 3,
        matches_played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 1,
        goals_against: 0,
        goal_difference: 1
    },
    {
        team: "aston villa",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 2,
        goals_against: 3,
        goal_difference:-1
    },
    {
        team: "manchester city",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 1,
        goal_difference:-1
    },
    {
        team: "wolves",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 1,
        goal_difference:-1
    },
    {
        team: "newcastle",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 2,
        goals_against: 4,
        goal_difference:-2
    },
    {
        team: "southampton",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 3,
        goal_difference:-2
    },
    {
        team: "arsenal",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 2,
        goal_difference:-2
    },
    {
        team: "burnley",
        points: 0,
        matches_played: 2,
        wins: 0,
        draws: 0,
        losses: 2,
        goals_for: 1,
        goals_against: 4,
        goal_difference:-3
    },
    {
        team: "crystal palace",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 3,
        goal_difference:-3
    },
    {
        team: "norwich city",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 3,
        goal_difference:-3
    },
    {
        team: "leeds united",
        points: 0,
        matches_played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 5,
        goal_difference:-4
    }
]